Repository go-gitea/tea, pull requests merged in 2019-04, with the labels that each got.

#9 fix comments and descriptions
  cmd/issues.go
  cmd/login.go
  cmd/pulls.go
  cmd/releases.go
Labels: lgtm/done

#11 Fix installation instructions
  README.md
Labels: lgtm/done

#18 skip empty pull requests (#17)
  cmd/pulls.go
Labels: bug, lgtm/done

#19 added 'go get' command & build instructions (#16)
  README.md
Labels: lgtm/done

#21 fix drone
  .drone.yml
  Makefile
Labels: kind/build, lgtm/done

#24 chore: go support combine all coverage file
  .drone.yml
  Makefile
  README.md
Labels: lgtm/done

#23 Add missing make-compress to fix release
  Makefile
Labels: kind/build, lgtm/done
